version: '3.7'

services:
  postgres:
    image: jsonslim/iht:pg-tag
    container_name: postgres
    environment:
      POSTGRES_USER: usr1 
      POSTGRES_PASSWORD: usr1
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    restart: always  

  microservice:
    image: jsonslim/iht:microservice-tag
    container_name: microservice_app
    working_dir: /usr/src/app
    ports:
      - "3001:3001"
    command: npm start
    restart: always

  mainapp:
    image: jsonslim/iht:mainapp-tag
    container_name: main_app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://usr1:usr1@postgres:5432/users
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm start"
    restart: always

volumes:
  postgres-data: